import javafx.collections.ObservableList;

/**
 * this class holds all the information
 * generated by the view components
 */
public class ViewComponentOutput {

    private String browserSongName;
    private String browserPath;

    private String selectedSong;
    private int selectedIndex;

    /**
     * gets the song name generated from the file chooser
     * @return
     */
    public String getBrowserSongName() {
        return browserSongName;
    }

    /**
     * sets the song name generated from the file chooser
     * @param browserSongName
     */
    public void setBrowserSongName(String browserSongName) {
        this.browserSongName = browserSongName;
    }

    /**
     * gets the song path generated from the file chooser
     * @return
     */
    public String getBrowserPath() {
        return browserPath;
    }

    /**
     * sets the song path generated from the file chooser
     * @param browserPath
     */
    public void setBrowserPath(String browserPath) {
        this.browserPath = browserPath;
    }

    /**
     * get the song currently selected on the TableView
     * @return
     */
    public String getSelectedSong() {
        return selectedSong;
    }

    /**
     * sets the song currently selected on the TableView
     * @param selectedSong
     */
    public void setSelectedSong(String selectedSong) {
        this.selectedSong = selectedSong;
    }

    /**
     * sets the TableView currently selected index.
     * @return
     */
    public int getSelectedIndex() {
        return selectedIndex;
    }

    /**
     * gets the TableView currently selected index.
     * @param selectedIndex
     */
    public void setSelectedIndex(int selectedIndex) {
        this.selectedIndex = selectedIndex;
    }
}
